num1 = 1000
num2 = 500
num3 = 1000

print (num1 > num2)#Mayor que...
print (num1 < num2)#Menor que...
print (num1 >= num3)#Mayor o igual que...
print (num1 <= num3)#Menor o mayor que...
print (num1 == num2)#Igual que...
print (num1 != num2)#Diferente que...

#Tambien se puede usar con strings

cadena = "Comparaciones con Strings"
cadena2 = "Comparacion de String"

print (cadena > cadena2)